# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(default=datetime.datetime(2017, 10, 4, 17, 57, 55, 814221, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
